import React from 'react';

interface DisclaimerProps {
  onBack: () => void;
}

const Disclaimer: React.FC<DisclaimerProps> = ({ onBack }) => {
  React.useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="bg-white rounded-2xl shadow-xl shadow-indigo-100/50 p-8 md:p-12 animate-fade-in">
      <div className="prose prose-slate max-w-none prose-p:leading-relaxed prose-h1:text-4xl prose-h1:font-bold prose-h1:text-transparent prose-h1:bg-clip-text prose-h1:bg-gradient-to-r prose-h1:from-blue-600 prose-h1:to-indigo-700 prose-h1:pb-4 prose-h2:border-b prose-h2:border-slate-200 prose-a:text-indigo-600 hover:prose-a:text-indigo-800 transition-colors">
        
        <button onClick={onBack} className="text-indigo-600 hover:text-indigo-800 font-semibold mb-8 no-underline focus:outline-none focus:ring-2 focus:ring-indigo-500 rounded-sm">&larr; Back to Counter</button>

        <h1>Disclaimer</h1>
        <p><strong>Last Updated:</strong> July 26, 2024</p>

        <h2>1. General Information Only</h2>
        <p>The information and tools provided by Character & Word Counter (the "Service") are for general informational purposes only. All information on the site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or calculations provided by the Service.</p>

        <h2>2. No Professional Advice</h2>
        <p>The Service provides a software-based text analysis tool. It does not provide professional advice of any kind (including but not limited to legal, SEO, marketing, academic, or editorial advice). The results generated by the tool, such as word counts, character counts, and other metrics, are based on automated algorithms and should not be solely relied upon for critical applications. Any action you take upon the information you find on this website is strictly at your own risk. You should consult with an appropriate professional for specific advice tailored to your situation.</p>

        <h2>3. Accuracy and Reliability of the Tool</h2>
        <p>We strive to make the Character & Word Counter tool as accurate and reliable as possible. However, the calculation of words, characters, paragraphs, and other text metrics can vary depending on the specific algorithm, language, and formatting used. Different software (e.g., Microsoft Word, Google Docs) may produce slightly different results. We do not guarantee that the counts provided by our tool will match those of other programs or meet specific requirements from third parties (such as academic institutions or publishers). It is your responsibility to verify the results for your specific needs.</p>

        <h2>4. External Links and Advertising Disclaimer</h2>
        <p>The Service may contain (or you may be sent through the Service) links to other websites or content belonging to or originating from third parties, primarily through advertisements. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising.</p>

        <h2>5. No Guarantees of Service Availability</h2>
        <p>While we make every effort to keep the Service available and running smoothly, we take no responsibility for, and will not be liable for, the Service being temporarily unavailable due to technical issues beyond our control. We do not guarantee uninterrupted, timely, or error-free access to the tool.</p>
        
        <h2>6. Limitation of Liability</h2>
        <p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the Service or reliance on any information provided by the Service. Your use of the Character & Word Counter and your reliance on any information from the tool is solely at your own risk. We are not responsible for any decisions made, or actions taken or not taken, based on the information provided by our tool. This includes, but is not limited to, failure to meet deadlines, submission of documents with incorrect formatting or counts, or any other negative consequences arising from the use or misuse of the Service.</p>

        <h2>7. User Responsibility</h2>
        <p>You acknowledge that you are using the Service voluntarily. You are responsible for double-checking all results and ensuring that your work meets the required specifications for its intended purpose. The tool is a supplementary aid, not a substitute for careful proofreading and verification.</p>

        <h2>8. Changes to This Disclaimer</h2>
        <p>We reserve the right to make additions, deletions, or modifications to the contents of this Disclaimer at any time without prior notice. We do not, however, make any commitment to update the information. We recommend you review this page periodically for any changes. By using this website, you are agreeing to be bound by the current version of this Disclaimer.</p>

        <h2>9. Contact Us</h2>
        <p>If you have any questions about this Disclaimer, please contact us at <a href="mailto:legal@characterwordcounter.com">legal@characterwordcounter.com</a>.</p>
      </div>
    </div>
  );
};

export default Disclaimer;